package_rename_config:
  android:
    app_name: Gita Sarathi
    package_name: com.gitasarathi
    override_old_package: com.example.chapter
    lang: # (Optional) (String) The android development language {kotlin(default) or java}
